### ISSUE TITLE
Example for NextJS 14 and Tailwind with App Router

### ISSUE THREAD

**Issue by gygabyte017** [primefaces/primereact-examples#19]
Hi, do you mind updating (or adding) the examples with nextjs+tailwind, styled and unstyled, using the new App Router in v14? I'm struggling about configuring the new `layout.tsx`, I managed to use Primereact OR Tailwind, but not both together.

Thank you
Regards

**Comment by melloware** [comment]
Issue has been asked under the Free Sakai React template as well: https://github.com/primefaces/sakai-react/issues/47

And open issue: https://github.com/primefaces/primereact/issues/5127

**Comment by nicolasGallegos** [comment]
Has Next14 been able to integrate with Prime React and Tailiwind?

**Comment by robsoncombr** [comment]
+1

**Comment by BanDroid** [comment]
i got news. nextjs 13+ with app router and tailwind could work together without the layer thing. just need to import the css theme.css below the globals.css in layout file. i figure this out after i got no styling at all even after following the tailwind instruction, turns out i got it working after switching these line.

```javascript
// this is the wrong order
import "primereact/resources/themes/md-dark-indigo/theme.css";
import "./globals.css";
```

```javascript
// this is the right order
import "./globals.css";
import "primereact/resources/themes/md-dark-indigo/theme.css";
```

**Comment by meowzhin** [comment]
> ```js
> import "primereact/resources/themes/md-dark-indigo/theme.css";
> ```

Can you share a complete configuration for this? Do we still need the `PrimeReactProvider`?

**Comment by BanDroid** [comment]
> > ```js
> > import "primereact/resources/themes/md-dark-indigo/theme.css";
> > ```
> 
> Hey man, nice! Can you share a complete configuration for this? Do we still need the `PrimeReactProvider`?

basically, no. The provider only hold state for components and themes, but the css only apply the style, and if the style applied in incorrect order, the tailwind will reset the primereact style cause it is tailwind behavior to reset any styling that applies before them.

**Comment by melloware** [comment]
@BanDroid i would love if you wanted to submit a PR for this example here in the examples folders because this gets asked a lot?

**Comment by BanDroid** [comment]
> @BanDroid i would love if you wanted to submit a PR for this example here in the examples folders because this gets asked a lot?

others need to confirm if my solution works or not, it works with mine, but if i'm not sure if this is working with someone else.

**Comment by meowzhin** [comment]
The only way I managed to work is by adding preflight as false in my tailwind.config.ts but this is a huge nuclear bomb so is not a solution but a workaround.

```
const config: Config = {
  corePlugins: {
    preflight: false,
  }
 ```
 
 I have no idea but this layers in global.css are doing jack.
 
 ```
@layer twbase, primereact, twutilities;

@import 'primereact/resources/themes/lara-light-indigo/theme.css' layer(primereact);

@layer twbase {
  @tailwind base;
}

@layer twutilities {
  @tailwind components;
  @tailwind utilities;
}
```

The issue itself is with the tailwind, not primereact because if you remove the tailwind either by disabling the preflight or by removing the layers and leaving just your theme in your global.css, it suddenly works.

@BanDroid, can you share a stackblitz so we can take a look? ❤️

**Comment by meowzhin** [comment]
SO... I was able to find a weird solution but I have NO IDEA why it works, I really don't understand.

The usual global.css

```
@layer tailwind-base, primereact, tailwind-utilities;

@import 'primereact/resources/themes/saga-blue/theme.css' layer(primereact);

@layer tailwind-base {
  @tailwind base;
}

@layer tailwind-utilities {
  @tailwind components;
  @tailwind utilities;
}
```

AND... 

Bro, I don't understand why.

Just add a second import with the actual theme you want to use in your `layout.tsx`

```
import "./globals.css";
import 'primereact/resources/themes/saga-blue/theme.css';
```

You can go either way with provider or not.

```
<PrimeReactProvider>
    {children}
</PrimeReactProvider>
```

Is this what you meant @BanDroid? We basically have to add the theme twice, one "dummy" and another one you actually want to use.

**Comment by BanDroid** [comment]
> Bro, I don't understand why.
> 
> Just add a second import with the actual theme you want to use in your `layout.tsx`
> 
> ```
> import "./globals.css";
> import 'primereact/resources/themes/saga-blue/theme.css';
> ```
> 
> You can go either way with provider or not.
> 
> ```
> <PrimeReactProvider>
>     {children}
> </PrimeReactProvider>
> ```
> 
> Is this what you meant @BanDroid? We basically have to add the theme twice, one "dummy" and another one you actually want to use.

yes, this is what i mean, you dont exactly need to import primereact in globals.css, cause primereact classes and tailwind classes have different prefixes, it will be different case if you also use primefaces (seriously, why? 2 utility library?)

**Comment by melloware** [comment]
Thanks to @BanDroid and @meowzhin a new sample has been added: https://github.com/primefaces/primereact-examples/tree/main/nextjs-app-router-styled-tailwind

**Comment by VytautasLozickas** [comment]
Trying to use the unstyled version like this:
```
<PrimeReactProvider
    value={{
        unstyled: true,
        pt: Tailwind,
        ptOptions: { mergeSections: true, mergeProps: true, classNameMergeFunction: twMerge },
}}>
    {children}
</PrimeReactProvider>
```
Causes an error when trying to pass `twMerge` into `classNameMergeFunction`:
```
[ Server ] Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {mergeSections: true, mergeProps: true, classNameMergeFunction: function callTailwindMerge}
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by BanDroid** [comment]
> Trying to use the unstyled version like this:
> ```
> <PrimeReactProvider
>     value={{
>         unstyled: true,
>         pt: Tailwind,
>         ptOptions: { mergeSections: true, mergeProps: true, classNameMergeFunction: twMerge },
>     }}>
>     {children}
> </PrimeReactProvider>
> ```
> Causes an error when trying to pass `twMerge` into `classNameMergeFunction`:
> ```
> [ Server ] Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
>   {mergeSections: true, mergeProps: true, classNameMergeFunction: function callTailwindMerge}
>                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```


the file where you create the `twMerge` function, add the "use client" directives, because your provider is client-component, but this `twMerge` function is in server, i'm not sure how you import the `twMerge`

**Comment by ussfranck** [comment]
https://github.com/primefaces/primereact-examples/issues/19#issuecomment-2290167875

That's right, and on my side, I can't figure out 100% why it works.
I can say it's because this config uses the @layer mechanism introduced by Tailwind CSS to manage styles in a modular way. Here's how it works:

1. @layer Directive
The @layer directive is used to define and manage specific style layers in Tailwind CSS. This allows styles to be structured into different layers: base, components and utilities.

tailwind-base: Contains the basic styles provided by Tailwind CSS.
primereact: Although this layer is defined, there is no direct import of PrimeReact styles here, probably for caching or optimization reasons.
tailwind-utilities: Contains Tailwind CSS components and utilities.

2. Tailwind style layers
@tailwind base: Applies basic styles such as CSS reset and default styles.
@tailwind components : Loads predefined or custom components.
@tailwind utilities: Loads utility classes such as bg-yellow-500, font-semibold, etc.

And so the @layer structure seems to allow Tailwind CSS and PrimeReact to coexist without style conflicts.
So it works - it's a pragmatic solution for integrating PrimeReact with Tailwind CSS in a Next.js(15) App router project, even if the technical explanation of this solution isn't completely clear to everyone
